options_dict = {
  'Afghani do Afeganistão' : 'AFN',
  'Ariary Madagascarense' : 'MGA',
  'Baht Tailandês' : 'THB',
  'Balboa Panamenho' : 'PAB',
  'Birr Etíope' : 'ETB',
  'Bitcoin' : 'BTC',
  'Bolívar Venezuelano' : 'VEF',
  'Boliviano' : 'BOB',
  'Brent Spot' : 'XBR',
  'Cedi Ganês' : 'GHS',
  'Colón Costarriquenho' : 'CRC',
  'Colon de El Salvador' : 'SVC',
  'Córdoba Nicaraguense' : 'NIO',
  'Coroa Checa' : 'CZK',
  'Coroa Dinamarquesa' : 'DKK',
  'Coroa Islandesa' : 'ISK',
  'Coroa Norueguesa' : 'NOK',
  'Coroa Sueca' : 'SEK',
  'Dalasi da Gâmbia' : 'GMD',
  'Denar Macedônio' : 'MKD',
  'Dinar Argelino' : 'DZD',
  'Dinar do Bahrein' : 'BHD',
  'Dinar Iraquiano' : 'IQD',
  'Dinar Jordaniano' : 'JOD',
  'Dinar Kuwaitiano' : 'KWD',
  'Dinar Líbio' : 'LYD',
  'Dinar Sérvio' : 'RSD',
  'Dinar Tunisiano' : 'TND',
  'Dirham dos Emirados': 'AED',
  'Dirham Marroquino' : 'MAD',
  'Dobra São Tomé/Príncipe' : 'STD',
  'Dogecoin' : 'DOGE',
  'Dólar Americano' : 'USD',
  'Dólar Australiano' : 'AUD',
  'Dólar Canadense' : 'CAD',
  'Dólar das Bahamas' : 'BSD',
  'Dólar das Ilhas Cayman' : 'KYD',
  'Dólar de Barbados' : 'BBD',
  'Dólar de Belize' : 'BZD',
  'Dólar de Brunei' : 'BND',
  'Dólar de Cingapura' : 'SGD',
  'Dólar de Fiji' : 'FJD',
  'Dólar de Hong Kong' : 'HKD',
  'Dólar de Trinidad' : 'TTD',
  'Dólar do Caribe Oriental' : 'XCD',
  'Dólar Jamaicano' : 'JMD',
  'Dólar Namíbio' : 'NAD',
  'Dólar Neozelandês' : 'NZD',
  'Dólar Taiuanês' : 'TWD',
  'Dólar Zimbabuense' : 'ZWL',
  'Dong Vietnamita' : 'VND',
  'Dram Armênio' : 'AMD',
  'DSE' : 'SDR',
  'Escudo cab :verdiano' : 'CVE',
  'Ethereum' : 'ETH',
  'Euro' : 'EUR',
  'Florim Húngaro' : 'HUF',
  'Franco Burundinense' : 'BIF',
  'Franco CFA Central' : 'XAF',
  'Franco CFA Ocidental' : 'XOF',
  'Franco CFP' : 'XPF',
  'Franco Comorense' : 'KMF',
  'Franco de Guiné' : 'GNF',
  'Franco do Djubouti' : 'DJF',
  'Franco Ruandês' : 'RWF',
  'Franco Suíço' : 'CHF',
  'Gourde Haitiano' : 'HTG',
  'Guarani Paraguaio' : 'PYG',
  'Guilder das Antilhas' : 'ANG',
  'Hryvinia Ucraniana' : 'UAH',
  'Iene Japonês' : 'JPY',
  'Kina Papu' : 'PGK',
  'Kip Laosiano' : 'LAK',
  'Kuna Croata' : 'HRK',
  'Kwacha Malauiana' : 'MWK',
  'Kwacha Zambiana' : 'ZMK',
  'Kwanza Angolano' : 'AOA',
  'Kyat de Mianmar' : 'MMK',
  'Lari Georgiano' : 'GEL',
  'Lek Albanês' : 'ALL',
  'Lempira Hondurenha' : 'HNL',
  'Leu Moldavo' : 'MDL',
  'Leu Romeno' : 'RON',
  'Lev Búlgaro' : 'BGN',
  'Libra Egípcia' : 'EGP',
  'Libra Esterlina' : 'GBP',
  'Libra Libanesa' : 'LBP',
  'Libra Síria' : 'SYP',
  'Libra Sudanesa' : 'SDG',
  'Lilangeni Suazilandês' : 'SZL',
  'Litecoin' : 'LTC',
  'Loti do Lesoto' : 'LSL',
  'Manat Azeri' : 'AZN',
  'Marco Conversível' : 'BAM',
  'Metical de Moçambique' : 'MZN',
  'Mongolian Tugrik' : 'MNT',
  'Naira Nigeriana' : 'NGN',
  'Nova Lira Turca' : 'TRY',
  'Novo Shekel Israelense' : 'ILS',
  'Ouguiya Mauritana' : 'MRO',
  'Pataca de Macau' : 'MOP',
  'Peso Argentino' : 'ARS',
  'Peso Chileno' : 'CLP',
  'Peso Colombiano' : 'COP',
  'Peso Cubano' : 'CUP',
  'Peso Dominicano' : 'DOP',
  'Peso Filipino' : 'PHP',
  'Peso Mexicano' : 'MXN',
  'Peso Uruguaio' : 'UYU',
  'Pula de Botswana' : 'BWP',
  'Quetzal Guatemalteco' :'GTQ',
  'Rand Su' : 'ZAR',
  'Real Brasileiro Turismo' : 'BRLT',
  'Real Brasileiro' : 'BRL',
  'Rial Catarense' : 'QAR',
  'Rial Iraniano' : 'IRR',
  'Rial Omanense' : 'OMR',
  'Riel Cambojano' : 'KHR',
  'Ringgit Malaio' : 'MYR',
  'Riyal Iemenita' : 'YER',
  'Riyal Saudita' : 'SAR',
  'Rublo Bielorrusso' : 'BYN',
  'Rublo Russo' : 'RUB',
  'Rufiyaa Maldiva' : 'MVR',
  'Rúpia de Sri Lanka' : 'LKR',
  'Rúpia Indiana' : 'INR',
  'Rupia Indonésia' : 'IDR',
  'Rúpia Mauriciana' : 'MUR',
  'Rúpia Nepalesa' : 'NPR',
  'Rúpia Paquistanesa' : 'PKR',
  'Rúpias de Seicheles' : 'SCR',
  'Shilling Queniano' : 'KES',
  'Shilling Somaliano' : 'SOS',
  'Shilling Tanzaniano' : 'TZS',
  'Shilling Ugandês' : 'UGX',
  'Sol do Peru' : 'PEN',
  'Som Quirguistanês' : 'KGS',
  'Som Uzbequistanês' : 'UZS',
  'Somoni do Tajiquistão' : 'TJS',
  'Taka de Bangladesh' : 'BDT',
  'Tengue Cazaquistanês' : 'KZT',
  'TMT' : 'TMT',
  'Vatu de Vanuatu' : 'VUV',
  'Won Sul Coreano' : 'KRW',
  'XPrata' : 'XAGG',
  'XRP' : 'XRP',
  'Yuan chinês offshore' : 'CNH',
  'Yuan Chinês' : 'CNY',
  'Zlóti Polonês' : 'PLN',
}

lista = [*options_dict]